services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    user: "1000:www-data"
    environment:
      APP_ENV: test
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    user: "1000:www-data"
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/dev.db"